In [3]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
import numpy as np
b=np.array([3,5,6,4,9,10])
print(b)

c=b*10
print(c)

c=b+b
print(c)

c=b.shape
print(c)
c=b.dtype
print(c)

[ 3  5  6  4  9 10]
[ 30  50  60  40  90 100]
[ 6 10 12  8 18 20]
(6,)
int32


In [21]:
import numpy as np
data=[0,1,8.4,6,7,10]
arr=np.array(data)
arr

data1=[[1,2,3,4],[5,3,9,10]]
arr1=np.array(data1)
arr1
arr1.ndim
arr1.shape
arr1.dtype
arr.dtype


dtype('float64')

In [30]:
import numpy as np
np.zeros(10)
np.zeros((2,3))
np.empty((3,5))

np.arange(17)
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[6,7,8]]])
arr
arr*arr
arr*0.5
1/arr

array([[[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667],
        [0.16666667, 0.14285714, 0.125     ]]])

In [60]:
import numpy as np
c=np.arange(10)
c[5:9]

arr=np.array([[[1,2,3],[4,3,2]],[[4,5,7],[5,8,3]]])
arr[0:1,1:0]

array([], shape=(1, 0, 3), dtype=int32)

In [67]:
import numpy as np
names=np.array(['Aveen','Saad','Faraz'])
names


array(['Aveen', 'Saad', 'Faraz'], dtype='<U5')

In [77]:
import numpy as np
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
data
data[2]
data[:2,1:]
data[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
import numpy as np
data=np.random.randn(7,4)
da

array([[-0.12275345],
       [ 0.10550945],
       [ 0.99959744],
       [ 0.6312845 ]])